
feignUrl: http://transaction.test.myoilbank.com
parter: inspector
apikey: 8e96c1fb87ac069c2a39f1ed61b10428
hystrix.command.default.execution.timeout.enabled: false
userDomin: http://user.test.myoilbank.com
#log
logging:
config: classpath:logback.xml

#aes 加解密
aeskey: "sinochemOILBANK1"
useaes: "true1"