
feignUrl: https://transaction9.myoilbank.com
parter: inspector
apikey: 8e96c1fb87ac069c2a39f1ed61b10428
hystrix.command.default.execution.timeout.enabled: false
userDomin: https://user9.myoilbank.com
#log
logging:
config: classpath:logback.xml

#aes 加解密
aeskey: "sinochemOILBANK1"
useaes: "true1"