package com.sinochem.crude.trade.wechat.domain;

import java.util.Date;

public class WechatLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_logs.id
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    private Integer id;

    public String getStrTime() {
        return StrTime;
    }

    public void setStrTime(String strTime) {
        StrTime = strTime;
    }

    private String StrTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_logs.type
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_logs.time
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_logs.servicename
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    private String servicename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_logs.desc
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_logs.id
     *
     * @return the value of wechat_logs.id
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_logs.id
     *
     * @param id the value for wechat_logs.id
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_logs.type
     *
     * @return the value of wechat_logs.type
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_logs.type
     *
     * @param type the value for wechat_logs.type
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_logs.time
     *
     * @return the value of wechat_logs.time
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_logs.time
     *
     * @param time the value for wechat_logs.time
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_logs.servicename
     *
     * @return the value of wechat_logs.servicename
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    public String getServicename() {
        return servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_logs.servicename
     *
     * @param servicename the value for wechat_logs.servicename
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    public void setServicename(String servicename) {
        this.servicename = servicename == null ? null : servicename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_logs.desc
     *
     * @return the value of wechat_logs.desc
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_logs.desc
     *
     * @param desc the value for wechat_logs.desc
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}