package com.sinochem.crude.trade.productOil.model;

import java.util.Date;

public class TCmsChannelSub {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.UUID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.CHANNEL_M_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Long channelMId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.CHANNEL_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.CHANNEL_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.CHANNEL_DESC
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String channelDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.CHANNEL_ORDER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Integer channelOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.CREATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.CREATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.UPDATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.ALIVE_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String aliveFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.EXTEND1
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.EXTEND2
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.EXTEND3
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.EXTEND4
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.EXTEND5
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.EXTEND6
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.EXTEND7
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.EXTEND8
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.EXTEND9
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_channel_sub.EXTEND10
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.ID
     *
     * @return the value of t_cms_channel_sub.ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.ID
     *
     * @param id the value for t_cms_channel_sub.ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.UUID
     *
     * @return the value of t_cms_channel_sub.UUID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.UUID
     *
     * @param uuid the value for t_cms_channel_sub.UUID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.CHANNEL_M_ID
     *
     * @return the value of t_cms_channel_sub.CHANNEL_M_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Long getChannelMId() {
        return channelMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.CHANNEL_M_ID
     *
     * @param channelMId the value for t_cms_channel_sub.CHANNEL_M_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setChannelMId(Long channelMId) {
        this.channelMId = channelMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.CHANNEL_CODE
     *
     * @return the value of t_cms_channel_sub.CHANNEL_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.CHANNEL_CODE
     *
     * @param channelCode the value for t_cms_channel_sub.CHANNEL_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.CHANNEL_NAME
     *
     * @return the value of t_cms_channel_sub.CHANNEL_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.CHANNEL_NAME
     *
     * @param channelName the value for t_cms_channel_sub.CHANNEL_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.CHANNEL_DESC
     *
     * @return the value of t_cms_channel_sub.CHANNEL_DESC
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getChannelDesc() {
        return channelDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.CHANNEL_DESC
     *
     * @param channelDesc the value for t_cms_channel_sub.CHANNEL_DESC
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setChannelDesc(String channelDesc) {
        this.channelDesc = channelDesc == null ? null : channelDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.CHANNEL_ORDER
     *
     * @return the value of t_cms_channel_sub.CHANNEL_ORDER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Integer getChannelOrder() {
        return channelOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.CHANNEL_ORDER
     *
     * @param channelOrder the value for t_cms_channel_sub.CHANNEL_ORDER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setChannelOrder(Integer channelOrder) {
        this.channelOrder = channelOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.CREATE_USER
     *
     * @return the value of t_cms_channel_sub.CREATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.CREATE_USER
     *
     * @param createUser the value for t_cms_channel_sub.CREATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.CREATE_DATE
     *
     * @return the value of t_cms_channel_sub.CREATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.CREATE_DATE
     *
     * @param createDate the value for t_cms_channel_sub.CREATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.UPDATE_USER
     *
     * @return the value of t_cms_channel_sub.UPDATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.UPDATE_USER
     *
     * @param updateUser the value for t_cms_channel_sub.UPDATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.UPDATE_DATE
     *
     * @return the value of t_cms_channel_sub.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.UPDATE_DATE
     *
     * @param updateDate the value for t_cms_channel_sub.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.ALIVE_FLAG
     *
     * @return the value of t_cms_channel_sub.ALIVE_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getAliveFlag() {
        return aliveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.ALIVE_FLAG
     *
     * @param aliveFlag the value for t_cms_channel_sub.ALIVE_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setAliveFlag(String aliveFlag) {
        this.aliveFlag = aliveFlag == null ? null : aliveFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.EXTEND1
     *
     * @return the value of t_cms_channel_sub.EXTEND1
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.EXTEND1
     *
     * @param extend1 the value for t_cms_channel_sub.EXTEND1
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.EXTEND2
     *
     * @return the value of t_cms_channel_sub.EXTEND2
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.EXTEND2
     *
     * @param extend2 the value for t_cms_channel_sub.EXTEND2
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.EXTEND3
     *
     * @return the value of t_cms_channel_sub.EXTEND3
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend3() {
        return extend3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.EXTEND3
     *
     * @param extend3 the value for t_cms_channel_sub.EXTEND3
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend3(String extend3) {
        this.extend3 = extend3 == null ? null : extend3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.EXTEND4
     *
     * @return the value of t_cms_channel_sub.EXTEND4
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend4() {
        return extend4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.EXTEND4
     *
     * @param extend4 the value for t_cms_channel_sub.EXTEND4
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend4(String extend4) {
        this.extend4 = extend4 == null ? null : extend4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.EXTEND5
     *
     * @return the value of t_cms_channel_sub.EXTEND5
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend5() {
        return extend5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.EXTEND5
     *
     * @param extend5 the value for t_cms_channel_sub.EXTEND5
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend5(String extend5) {
        this.extend5 = extend5 == null ? null : extend5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.EXTEND6
     *
     * @return the value of t_cms_channel_sub.EXTEND6
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend6() {
        return extend6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.EXTEND6
     *
     * @param extend6 the value for t_cms_channel_sub.EXTEND6
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend6(String extend6) {
        this.extend6 = extend6 == null ? null : extend6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.EXTEND7
     *
     * @return the value of t_cms_channel_sub.EXTEND7
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend7() {
        return extend7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.EXTEND7
     *
     * @param extend7 the value for t_cms_channel_sub.EXTEND7
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend7(String extend7) {
        this.extend7 = extend7 == null ? null : extend7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.EXTEND8
     *
     * @return the value of t_cms_channel_sub.EXTEND8
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend8() {
        return extend8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.EXTEND8
     *
     * @param extend8 the value for t_cms_channel_sub.EXTEND8
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend8(String extend8) {
        this.extend8 = extend8 == null ? null : extend8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.EXTEND9
     *
     * @return the value of t_cms_channel_sub.EXTEND9
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend9() {
        return extend9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.EXTEND9
     *
     * @param extend9 the value for t_cms_channel_sub.EXTEND9
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend9(String extend9) {
        this.extend9 = extend9 == null ? null : extend9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_channel_sub.EXTEND10
     *
     * @return the value of t_cms_channel_sub.EXTEND10
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend10() {
        return extend10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_channel_sub.EXTEND10
     *
     * @param extend10 the value for t_cms_channel_sub.EXTEND10
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend10(String extend10) {
        this.extend10 = extend10 == null ? null : extend10.trim();
    }
}