package com.sinochem.crude.trade.productOil.model;

import java.math.BigDecimal;
import java.util.Date;

public class TCmsDomesticProductPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.UUID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.PRODUCT_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.PRODUCT_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.HIGH_PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private BigDecimal highPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.LOW_PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private BigDecimal lowPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.PRICE_UNIT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String priceUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.PRICE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date priceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.AREA_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.AREA_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.PRICE_SOURCE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String priceSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.PRICE_TREND
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String priceTrend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.PRICE_CHANGE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private BigDecimal priceChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.CREATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.CREATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.UPDATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.ALIVE_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String aliveFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.EXTEND1
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.EXTEND2
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.EXTEND3
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.EXTEND4
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.EXTEND5
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.EXTEND6
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.EXTEND7
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.EXTEND8
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.EXTEND9
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.EXTEND10
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.HIGH_PRICE_CHANGE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private BigDecimal highPriceChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.LOW_PRICE_CHANGE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private BigDecimal lowPriceChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.PRE_HIGH_PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private BigDecimal preHighPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_domestic_product_price.PRE_LOW_PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private BigDecimal preLowPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.ID
     *
     * @return the value of t_cms_domestic_product_price.ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.ID
     *
     * @param id the value for t_cms_domestic_product_price.ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.UUID
     *
     * @return the value of t_cms_domestic_product_price.UUID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.UUID
     *
     * @param uuid the value for t_cms_domestic_product_price.UUID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.PRODUCT_CODE
     *
     * @return the value of t_cms_domestic_product_price.PRODUCT_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.PRODUCT_CODE
     *
     * @param productCode the value for t_cms_domestic_product_price.PRODUCT_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.PRODUCT_NAME
     *
     * @return the value of t_cms_domestic_product_price.PRODUCT_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.PRODUCT_NAME
     *
     * @param productName the value for t_cms_domestic_product_price.PRODUCT_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.PRICE
     *
     * @return the value of t_cms_domestic_product_price.PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.PRICE
     *
     * @param price the value for t_cms_domestic_product_price.PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.HIGH_PRICE
     *
     * @return the value of t_cms_domestic_product_price.HIGH_PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public BigDecimal getHighPrice() {
        return highPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.HIGH_PRICE
     *
     * @param highPrice the value for t_cms_domestic_product_price.HIGH_PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setHighPrice(BigDecimal highPrice) {
        this.highPrice = highPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.LOW_PRICE
     *
     * @return the value of t_cms_domestic_product_price.LOW_PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public BigDecimal getLowPrice() {
        return lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.LOW_PRICE
     *
     * @param lowPrice the value for t_cms_domestic_product_price.LOW_PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setLowPrice(BigDecimal lowPrice) {
        this.lowPrice = lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.PRICE_UNIT
     *
     * @return the value of t_cms_domestic_product_price.PRICE_UNIT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getPriceUnit() {
        return priceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.PRICE_UNIT
     *
     * @param priceUnit the value for t_cms_domestic_product_price.PRICE_UNIT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setPriceUnit(String priceUnit) {
        this.priceUnit = priceUnit == null ? null : priceUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.PRICE_DATE
     *
     * @return the value of t_cms_domestic_product_price.PRICE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getPriceDate() {
        return priceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.PRICE_DATE
     *
     * @param priceDate the value for t_cms_domestic_product_price.PRICE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setPriceDate(Date priceDate) {
        this.priceDate = priceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.AREA_CODE
     *
     * @return the value of t_cms_domestic_product_price.AREA_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.AREA_CODE
     *
     * @param areaCode the value for t_cms_domestic_product_price.AREA_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.AREA_NAME
     *
     * @return the value of t_cms_domestic_product_price.AREA_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.AREA_NAME
     *
     * @param areaName the value for t_cms_domestic_product_price.AREA_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.PRICE_SOURCE
     *
     * @return the value of t_cms_domestic_product_price.PRICE_SOURCE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getPriceSource() {
        return priceSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.PRICE_SOURCE
     *
     * @param priceSource the value for t_cms_domestic_product_price.PRICE_SOURCE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setPriceSource(String priceSource) {
        this.priceSource = priceSource == null ? null : priceSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.PRICE_TREND
     *
     * @return the value of t_cms_domestic_product_price.PRICE_TREND
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getPriceTrend() {
        return priceTrend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.PRICE_TREND
     *
     * @param priceTrend the value for t_cms_domestic_product_price.PRICE_TREND
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setPriceTrend(String priceTrend) {
        this.priceTrend = priceTrend == null ? null : priceTrend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.PRICE_CHANGE
     *
     * @return the value of t_cms_domestic_product_price.PRICE_CHANGE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public BigDecimal getPriceChange() {
        return priceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.PRICE_CHANGE
     *
     * @param priceChange the value for t_cms_domestic_product_price.PRICE_CHANGE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setPriceChange(BigDecimal priceChange) {
        this.priceChange = priceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.CREATE_USER
     *
     * @return the value of t_cms_domestic_product_price.CREATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.CREATE_USER
     *
     * @param createUser the value for t_cms_domestic_product_price.CREATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.CREATE_DATE
     *
     * @return the value of t_cms_domestic_product_price.CREATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.CREATE_DATE
     *
     * @param createDate the value for t_cms_domestic_product_price.CREATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.UPDATE_USER
     *
     * @return the value of t_cms_domestic_product_price.UPDATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.UPDATE_USER
     *
     * @param updateUser the value for t_cms_domestic_product_price.UPDATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.UPDATE_DATE
     *
     * @return the value of t_cms_domestic_product_price.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.UPDATE_DATE
     *
     * @param updateDate the value for t_cms_domestic_product_price.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.ALIVE_FLAG
     *
     * @return the value of t_cms_domestic_product_price.ALIVE_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getAliveFlag() {
        return aliveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.ALIVE_FLAG
     *
     * @param aliveFlag the value for t_cms_domestic_product_price.ALIVE_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setAliveFlag(String aliveFlag) {
        this.aliveFlag = aliveFlag == null ? null : aliveFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.EXTEND1
     *
     * @return the value of t_cms_domestic_product_price.EXTEND1
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.EXTEND1
     *
     * @param extend1 the value for t_cms_domestic_product_price.EXTEND1
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.EXTEND2
     *
     * @return the value of t_cms_domestic_product_price.EXTEND2
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.EXTEND2
     *
     * @param extend2 the value for t_cms_domestic_product_price.EXTEND2
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.EXTEND3
     *
     * @return the value of t_cms_domestic_product_price.EXTEND3
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend3() {
        return extend3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.EXTEND3
     *
     * @param extend3 the value for t_cms_domestic_product_price.EXTEND3
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend3(String extend3) {
        this.extend3 = extend3 == null ? null : extend3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.EXTEND4
     *
     * @return the value of t_cms_domestic_product_price.EXTEND4
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend4() {
        return extend4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.EXTEND4
     *
     * @param extend4 the value for t_cms_domestic_product_price.EXTEND4
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend4(String extend4) {
        this.extend4 = extend4 == null ? null : extend4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.EXTEND5
     *
     * @return the value of t_cms_domestic_product_price.EXTEND5
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend5() {
        return extend5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.EXTEND5
     *
     * @param extend5 the value for t_cms_domestic_product_price.EXTEND5
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend5(String extend5) {
        this.extend5 = extend5 == null ? null : extend5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.EXTEND6
     *
     * @return the value of t_cms_domestic_product_price.EXTEND6
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend6() {
        return extend6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.EXTEND6
     *
     * @param extend6 the value for t_cms_domestic_product_price.EXTEND6
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend6(String extend6) {
        this.extend6 = extend6 == null ? null : extend6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.EXTEND7
     *
     * @return the value of t_cms_domestic_product_price.EXTEND7
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend7() {
        return extend7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.EXTEND7
     *
     * @param extend7 the value for t_cms_domestic_product_price.EXTEND7
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend7(String extend7) {
        this.extend7 = extend7 == null ? null : extend7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.EXTEND8
     *
     * @return the value of t_cms_domestic_product_price.EXTEND8
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend8() {
        return extend8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.EXTEND8
     *
     * @param extend8 the value for t_cms_domestic_product_price.EXTEND8
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend8(String extend8) {
        this.extend8 = extend8 == null ? null : extend8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.EXTEND9
     *
     * @return the value of t_cms_domestic_product_price.EXTEND9
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend9() {
        return extend9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.EXTEND9
     *
     * @param extend9 the value for t_cms_domestic_product_price.EXTEND9
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend9(String extend9) {
        this.extend9 = extend9 == null ? null : extend9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.EXTEND10
     *
     * @return the value of t_cms_domestic_product_price.EXTEND10
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend10() {
        return extend10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.EXTEND10
     *
     * @param extend10 the value for t_cms_domestic_product_price.EXTEND10
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend10(String extend10) {
        this.extend10 = extend10 == null ? null : extend10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.HIGH_PRICE_CHANGE
     *
     * @return the value of t_cms_domestic_product_price.HIGH_PRICE_CHANGE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public BigDecimal getHighPriceChange() {
        return highPriceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.HIGH_PRICE_CHANGE
     *
     * @param highPriceChange the value for t_cms_domestic_product_price.HIGH_PRICE_CHANGE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setHighPriceChange(BigDecimal highPriceChange) {
        this.highPriceChange = highPriceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.LOW_PRICE_CHANGE
     *
     * @return the value of t_cms_domestic_product_price.LOW_PRICE_CHANGE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public BigDecimal getLowPriceChange() {
        return lowPriceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.LOW_PRICE_CHANGE
     *
     * @param lowPriceChange the value for t_cms_domestic_product_price.LOW_PRICE_CHANGE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setLowPriceChange(BigDecimal lowPriceChange) {
        this.lowPriceChange = lowPriceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.PRE_HIGH_PRICE
     *
     * @return the value of t_cms_domestic_product_price.PRE_HIGH_PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public BigDecimal getPreHighPrice() {
        return preHighPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.PRE_HIGH_PRICE
     *
     * @param preHighPrice the value for t_cms_domestic_product_price.PRE_HIGH_PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setPreHighPrice(BigDecimal preHighPrice) {
        this.preHighPrice = preHighPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_domestic_product_price.PRE_LOW_PRICE
     *
     * @return the value of t_cms_domestic_product_price.PRE_LOW_PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public BigDecimal getPreLowPrice() {
        return preLowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_domestic_product_price.PRE_LOW_PRICE
     *
     * @param preLowPrice the value for t_cms_domestic_product_price.PRE_LOW_PRICE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setPreLowPrice(BigDecimal preLowPrice) {
        this.preLowPrice = preLowPrice;
    }
}