package com.sinochem.crude.trade.productOil.model;

import java.util.Date;

public class TCmsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.UUID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.INFO_GRAB_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String infoGrabId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.CHANNEL_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Long channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.TITLE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.SHORT_TITLE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String shortTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.GENERAL
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String general;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.ORIGIN
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.ORIGIN_URL
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String originUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.AUTHOR
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.INFORMATION_TYPE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String informationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.SELECTED_ENDTIME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date selectedEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.STICK
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String stick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.STICK_EDNTIME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date stickEdntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.HAS_TITLE_IMG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String hasTitleImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.RECOMMEND_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String recommendFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.STATUS
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.BROWSE_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Integer browseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.COMMENT_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.SHARE_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Integer shareCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.COLLECTION_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Integer collectionCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.FABULOUS_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Integer fabulousCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.TRAMPLE_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Integer trampleCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.DESCRIPTION
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.VALID_BEGIN
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date validBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.VALID_END
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date validEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.VOID_PATH
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String voidPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.DISPLAY_MODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String displayMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.BIZ_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String bizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.ARTICLE_TYPE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String articleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.PROBATION_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String probationFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.IS_SHOW_GENERAL
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String isShowGeneral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.IS_SHOW_ORIGIN
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String isShowOrigin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.IS_SHOW_COPYRIGHT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String isShowCopyright;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.IS_SHOW_DISCLAIMER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String isShowDisclaimer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.IS_SHOW_AUTHOR
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String isShowAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.RELEASE_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String releaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.RELEASE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date releaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.REVIEWER_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String reviewerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.REVIEWER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String reviewer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.AUDIT_TIME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.REVOKE_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String revokeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.REVOKER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String revoker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.REVOKE_TIME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date revokeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.RESUFE_REMARK
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String resufeRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.TAG_LIST
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String tagList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.CREATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.CREATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.UPDATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.ALIVE_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String aliveFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.EXTEND2
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.EXTEND3
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.EXTEND4
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.EXTEND5
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.EXTEND6
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.EXTEND7
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.EXTEND8
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.EXTEND9
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.EXTEND10
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_info.EXTEND1
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String extend1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.ID
     *
     * @return the value of t_cms_info.ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.ID
     *
     * @param id the value for t_cms_info.ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.UUID
     *
     * @return the value of t_cms_info.UUID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.UUID
     *
     * @param uuid the value for t_cms_info.UUID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.INFO_GRAB_ID
     *
     * @return the value of t_cms_info.INFO_GRAB_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getInfoGrabId() {
        return infoGrabId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.INFO_GRAB_ID
     *
     * @param infoGrabId the value for t_cms_info.INFO_GRAB_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setInfoGrabId(String infoGrabId) {
        this.infoGrabId = infoGrabId == null ? null : infoGrabId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.CHANNEL_ID
     *
     * @return the value of t_cms_info.CHANNEL_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.CHANNEL_ID
     *
     * @param channelId the value for t_cms_info.CHANNEL_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.TITLE
     *
     * @return the value of t_cms_info.TITLE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.TITLE
     *
     * @param title the value for t_cms_info.TITLE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.SHORT_TITLE
     *
     * @return the value of t_cms_info.SHORT_TITLE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getShortTitle() {
        return shortTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.SHORT_TITLE
     *
     * @param shortTitle the value for t_cms_info.SHORT_TITLE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setShortTitle(String shortTitle) {
        this.shortTitle = shortTitle == null ? null : shortTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.GENERAL
     *
     * @return the value of t_cms_info.GENERAL
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getGeneral() {
        return general;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.GENERAL
     *
     * @param general the value for t_cms_info.GENERAL
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setGeneral(String general) {
        this.general = general == null ? null : general.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.ORIGIN
     *
     * @return the value of t_cms_info.ORIGIN
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.ORIGIN
     *
     * @param origin the value for t_cms_info.ORIGIN
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.ORIGIN_URL
     *
     * @return the value of t_cms_info.ORIGIN_URL
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getOriginUrl() {
        return originUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.ORIGIN_URL
     *
     * @param originUrl the value for t_cms_info.ORIGIN_URL
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setOriginUrl(String originUrl) {
        this.originUrl = originUrl == null ? null : originUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.AUTHOR
     *
     * @return the value of t_cms_info.AUTHOR
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.AUTHOR
     *
     * @param author the value for t_cms_info.AUTHOR
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.INFORMATION_TYPE
     *
     * @return the value of t_cms_info.INFORMATION_TYPE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getInformationType() {
        return informationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.INFORMATION_TYPE
     *
     * @param informationType the value for t_cms_info.INFORMATION_TYPE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setInformationType(String informationType) {
        this.informationType = informationType == null ? null : informationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.SELECTED_ENDTIME
     *
     * @return the value of t_cms_info.SELECTED_ENDTIME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getSelectedEndtime() {
        return selectedEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.SELECTED_ENDTIME
     *
     * @param selectedEndtime the value for t_cms_info.SELECTED_ENDTIME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setSelectedEndtime(Date selectedEndtime) {
        this.selectedEndtime = selectedEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.STICK
     *
     * @return the value of t_cms_info.STICK
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getStick() {
        return stick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.STICK
     *
     * @param stick the value for t_cms_info.STICK
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setStick(String stick) {
        this.stick = stick == null ? null : stick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.STICK_EDNTIME
     *
     * @return the value of t_cms_info.STICK_EDNTIME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getStickEdntime() {
        return stickEdntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.STICK_EDNTIME
     *
     * @param stickEdntime the value for t_cms_info.STICK_EDNTIME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setStickEdntime(Date stickEdntime) {
        this.stickEdntime = stickEdntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.HAS_TITLE_IMG
     *
     * @return the value of t_cms_info.HAS_TITLE_IMG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getHasTitleImg() {
        return hasTitleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.HAS_TITLE_IMG
     *
     * @param hasTitleImg the value for t_cms_info.HAS_TITLE_IMG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setHasTitleImg(String hasTitleImg) {
        this.hasTitleImg = hasTitleImg == null ? null : hasTitleImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.RECOMMEND_FLAG
     *
     * @return the value of t_cms_info.RECOMMEND_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getRecommendFlag() {
        return recommendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.RECOMMEND_FLAG
     *
     * @param recommendFlag the value for t_cms_info.RECOMMEND_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setRecommendFlag(String recommendFlag) {
        this.recommendFlag = recommendFlag == null ? null : recommendFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.STATUS
     *
     * @return the value of t_cms_info.STATUS
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.STATUS
     *
     * @param status the value for t_cms_info.STATUS
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.BROWSE_COUNT
     *
     * @return the value of t_cms_info.BROWSE_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Integer getBrowseCount() {
        return browseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.BROWSE_COUNT
     *
     * @param browseCount the value for t_cms_info.BROWSE_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setBrowseCount(Integer browseCount) {
        this.browseCount = browseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.COMMENT_COUNT
     *
     * @return the value of t_cms_info.COMMENT_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.COMMENT_COUNT
     *
     * @param commentCount the value for t_cms_info.COMMENT_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.SHARE_COUNT
     *
     * @return the value of t_cms_info.SHARE_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Integer getShareCount() {
        return shareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.SHARE_COUNT
     *
     * @param shareCount the value for t_cms_info.SHARE_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setShareCount(Integer shareCount) {
        this.shareCount = shareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.COLLECTION_COUNT
     *
     * @return the value of t_cms_info.COLLECTION_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Integer getCollectionCount() {
        return collectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.COLLECTION_COUNT
     *
     * @param collectionCount the value for t_cms_info.COLLECTION_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setCollectionCount(Integer collectionCount) {
        this.collectionCount = collectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.FABULOUS_COUNT
     *
     * @return the value of t_cms_info.FABULOUS_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Integer getFabulousCount() {
        return fabulousCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.FABULOUS_COUNT
     *
     * @param fabulousCount the value for t_cms_info.FABULOUS_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setFabulousCount(Integer fabulousCount) {
        this.fabulousCount = fabulousCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.TRAMPLE_COUNT
     *
     * @return the value of t_cms_info.TRAMPLE_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Integer getTrampleCount() {
        return trampleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.TRAMPLE_COUNT
     *
     * @param trampleCount the value for t_cms_info.TRAMPLE_COUNT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setTrampleCount(Integer trampleCount) {
        this.trampleCount = trampleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.DESCRIPTION
     *
     * @return the value of t_cms_info.DESCRIPTION
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.DESCRIPTION
     *
     * @param description the value for t_cms_info.DESCRIPTION
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.VALID_BEGIN
     *
     * @return the value of t_cms_info.VALID_BEGIN
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getValidBegin() {
        return validBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.VALID_BEGIN
     *
     * @param validBegin the value for t_cms_info.VALID_BEGIN
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setValidBegin(Date validBegin) {
        this.validBegin = validBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.VALID_END
     *
     * @return the value of t_cms_info.VALID_END
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getValidEnd() {
        return validEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.VALID_END
     *
     * @param validEnd the value for t_cms_info.VALID_END
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setValidEnd(Date validEnd) {
        this.validEnd = validEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.VOID_PATH
     *
     * @return the value of t_cms_info.VOID_PATH
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getVoidPath() {
        return voidPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.VOID_PATH
     *
     * @param voidPath the value for t_cms_info.VOID_PATH
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setVoidPath(String voidPath) {
        this.voidPath = voidPath == null ? null : voidPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.DISPLAY_MODE
     *
     * @return the value of t_cms_info.DISPLAY_MODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getDisplayMode() {
        return displayMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.DISPLAY_MODE
     *
     * @param displayMode the value for t_cms_info.DISPLAY_MODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setDisplayMode(String displayMode) {
        this.displayMode = displayMode == null ? null : displayMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.BIZ_ID
     *
     * @return the value of t_cms_info.BIZ_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.BIZ_ID
     *
     * @param bizId the value for t_cms_info.BIZ_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setBizId(String bizId) {
        this.bizId = bizId == null ? null : bizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.ARTICLE_TYPE
     *
     * @return the value of t_cms_info.ARTICLE_TYPE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getArticleType() {
        return articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.ARTICLE_TYPE
     *
     * @param articleType the value for t_cms_info.ARTICLE_TYPE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setArticleType(String articleType) {
        this.articleType = articleType == null ? null : articleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.PROBATION_FLAG
     *
     * @return the value of t_cms_info.PROBATION_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getProbationFlag() {
        return probationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.PROBATION_FLAG
     *
     * @param probationFlag the value for t_cms_info.PROBATION_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setProbationFlag(String probationFlag) {
        this.probationFlag = probationFlag == null ? null : probationFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.IS_SHOW_GENERAL
     *
     * @return the value of t_cms_info.IS_SHOW_GENERAL
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getIsShowGeneral() {
        return isShowGeneral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.IS_SHOW_GENERAL
     *
     * @param isShowGeneral the value for t_cms_info.IS_SHOW_GENERAL
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setIsShowGeneral(String isShowGeneral) {
        this.isShowGeneral = isShowGeneral == null ? null : isShowGeneral.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.IS_SHOW_ORIGIN
     *
     * @return the value of t_cms_info.IS_SHOW_ORIGIN
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getIsShowOrigin() {
        return isShowOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.IS_SHOW_ORIGIN
     *
     * @param isShowOrigin the value for t_cms_info.IS_SHOW_ORIGIN
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setIsShowOrigin(String isShowOrigin) {
        this.isShowOrigin = isShowOrigin == null ? null : isShowOrigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.IS_SHOW_COPYRIGHT
     *
     * @return the value of t_cms_info.IS_SHOW_COPYRIGHT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getIsShowCopyright() {
        return isShowCopyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.IS_SHOW_COPYRIGHT
     *
     * @param isShowCopyright the value for t_cms_info.IS_SHOW_COPYRIGHT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setIsShowCopyright(String isShowCopyright) {
        this.isShowCopyright = isShowCopyright == null ? null : isShowCopyright.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.IS_SHOW_DISCLAIMER
     *
     * @return the value of t_cms_info.IS_SHOW_DISCLAIMER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getIsShowDisclaimer() {
        return isShowDisclaimer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.IS_SHOW_DISCLAIMER
     *
     * @param isShowDisclaimer the value for t_cms_info.IS_SHOW_DISCLAIMER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setIsShowDisclaimer(String isShowDisclaimer) {
        this.isShowDisclaimer = isShowDisclaimer == null ? null : isShowDisclaimer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.IS_SHOW_AUTHOR
     *
     * @return the value of t_cms_info.IS_SHOW_AUTHOR
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getIsShowAuthor() {
        return isShowAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.IS_SHOW_AUTHOR
     *
     * @param isShowAuthor the value for t_cms_info.IS_SHOW_AUTHOR
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setIsShowAuthor(String isShowAuthor) {
        this.isShowAuthor = isShowAuthor == null ? null : isShowAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.RELEASE_ID
     *
     * @return the value of t_cms_info.RELEASE_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getReleaseId() {
        return releaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.RELEASE_ID
     *
     * @param releaseId the value for t_cms_info.RELEASE_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setReleaseId(String releaseId) {
        this.releaseId = releaseId == null ? null : releaseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.RELEASE_DATE
     *
     * @return the value of t_cms_info.RELEASE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.RELEASE_DATE
     *
     * @param releaseDate the value for t_cms_info.RELEASE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.REVIEWER_ID
     *
     * @return the value of t_cms_info.REVIEWER_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getReviewerId() {
        return reviewerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.REVIEWER_ID
     *
     * @param reviewerId the value for t_cms_info.REVIEWER_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setReviewerId(String reviewerId) {
        this.reviewerId = reviewerId == null ? null : reviewerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.REVIEWER
     *
     * @return the value of t_cms_info.REVIEWER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.REVIEWER
     *
     * @param reviewer the value for t_cms_info.REVIEWER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setReviewer(String reviewer) {
        this.reviewer = reviewer == null ? null : reviewer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.AUDIT_TIME
     *
     * @return the value of t_cms_info.AUDIT_TIME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.AUDIT_TIME
     *
     * @param auditTime the value for t_cms_info.AUDIT_TIME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.REVOKE_ID
     *
     * @return the value of t_cms_info.REVOKE_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getRevokeId() {
        return revokeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.REVOKE_ID
     *
     * @param revokeId the value for t_cms_info.REVOKE_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setRevokeId(String revokeId) {
        this.revokeId = revokeId == null ? null : revokeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.REVOKER
     *
     * @return the value of t_cms_info.REVOKER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getRevoker() {
        return revoker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.REVOKER
     *
     * @param revoker the value for t_cms_info.REVOKER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setRevoker(String revoker) {
        this.revoker = revoker == null ? null : revoker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.REVOKE_TIME
     *
     * @return the value of t_cms_info.REVOKE_TIME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getRevokeTime() {
        return revokeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.REVOKE_TIME
     *
     * @param revokeTime the value for t_cms_info.REVOKE_TIME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setRevokeTime(Date revokeTime) {
        this.revokeTime = revokeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.RESUFE_REMARK
     *
     * @return the value of t_cms_info.RESUFE_REMARK
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getResufeRemark() {
        return resufeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.RESUFE_REMARK
     *
     * @param resufeRemark the value for t_cms_info.RESUFE_REMARK
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setResufeRemark(String resufeRemark) {
        this.resufeRemark = resufeRemark == null ? null : resufeRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.TAG_LIST
     *
     * @return the value of t_cms_info.TAG_LIST
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getTagList() {
        return tagList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.TAG_LIST
     *
     * @param tagList the value for t_cms_info.TAG_LIST
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setTagList(String tagList) {
        this.tagList = tagList == null ? null : tagList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.CREATE_USER
     *
     * @return the value of t_cms_info.CREATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.CREATE_USER
     *
     * @param createUser the value for t_cms_info.CREATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.CREATE_DATE
     *
     * @return the value of t_cms_info.CREATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.CREATE_DATE
     *
     * @param createDate the value for t_cms_info.CREATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.UPDATE_USER
     *
     * @return the value of t_cms_info.UPDATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.UPDATE_USER
     *
     * @param updateUser the value for t_cms_info.UPDATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.UPDATE_DATE
     *
     * @return the value of t_cms_info.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.UPDATE_DATE
     *
     * @param updateDate the value for t_cms_info.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.ALIVE_FLAG
     *
     * @return the value of t_cms_info.ALIVE_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getAliveFlag() {
        return aliveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.ALIVE_FLAG
     *
     * @param aliveFlag the value for t_cms_info.ALIVE_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setAliveFlag(String aliveFlag) {
        this.aliveFlag = aliveFlag == null ? null : aliveFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.EXTEND2
     *
     * @return the value of t_cms_info.EXTEND2
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.EXTEND2
     *
     * @param extend2 the value for t_cms_info.EXTEND2
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.EXTEND3
     *
     * @return the value of t_cms_info.EXTEND3
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend3() {
        return extend3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.EXTEND3
     *
     * @param extend3 the value for t_cms_info.EXTEND3
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend3(String extend3) {
        this.extend3 = extend3 == null ? null : extend3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.EXTEND4
     *
     * @return the value of t_cms_info.EXTEND4
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend4() {
        return extend4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.EXTEND4
     *
     * @param extend4 the value for t_cms_info.EXTEND4
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend4(String extend4) {
        this.extend4 = extend4 == null ? null : extend4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.EXTEND5
     *
     * @return the value of t_cms_info.EXTEND5
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend5() {
        return extend5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.EXTEND5
     *
     * @param extend5 the value for t_cms_info.EXTEND5
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend5(String extend5) {
        this.extend5 = extend5 == null ? null : extend5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.EXTEND6
     *
     * @return the value of t_cms_info.EXTEND6
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend6() {
        return extend6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.EXTEND6
     *
     * @param extend6 the value for t_cms_info.EXTEND6
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend6(String extend6) {
        this.extend6 = extend6 == null ? null : extend6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.EXTEND7
     *
     * @return the value of t_cms_info.EXTEND7
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend7() {
        return extend7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.EXTEND7
     *
     * @param extend7 the value for t_cms_info.EXTEND7
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend7(String extend7) {
        this.extend7 = extend7 == null ? null : extend7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.EXTEND8
     *
     * @return the value of t_cms_info.EXTEND8
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend8() {
        return extend8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.EXTEND8
     *
     * @param extend8 the value for t_cms_info.EXTEND8
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend8(String extend8) {
        this.extend8 = extend8 == null ? null : extend8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.EXTEND9
     *
     * @return the value of t_cms_info.EXTEND9
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend9() {
        return extend9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.EXTEND9
     *
     * @param extend9 the value for t_cms_info.EXTEND9
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend9(String extend9) {
        this.extend9 = extend9 == null ? null : extend9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.EXTEND10
     *
     * @return the value of t_cms_info.EXTEND10
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend10() {
        return extend10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.EXTEND10
     *
     * @param extend10 the value for t_cms_info.EXTEND10
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend10(String extend10) {
        this.extend10 = extend10 == null ? null : extend10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_info.EXTEND1
     *
     * @return the value of t_cms_info.EXTEND1
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_info.EXTEND1
     *
     * @param extend1 the value for t_cms_info.EXTEND1
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }
}