package com.sinochem.crude.trade.productOil.model;

import java.util.Date;

public class TSysCodeSet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.MODEL_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String modelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.SET_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String setCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.SET_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String setName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.ITEM_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.ITEM_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.ITEM_SORT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Integer itemSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.ITEM_PARENT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String itemParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.ITEM_RELATION
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String itemRelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.IS_EDIT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String isEdit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.PLAT_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String platCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.ITEM_DESC
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String itemDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.ITEM_LEVEL
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Integer itemLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.REMARK
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.STATUS
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.CREATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.CREATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.UPDATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.ALIVE_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String aliveFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.MARKET_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String marketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.LANG_VER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String langVer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.EXT1
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.EXT2
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.EXT3
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String ext3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.EXT4
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String ext4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.EXT5
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String ext5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.EXT6
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String ext6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.EXT7
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String ext7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.EXT8
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String ext8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.EXT9
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String ext9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code_set.EXT10
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    private String ext10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.ID
     *
     * @return the value of t_sys_code_set.ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.ID
     *
     * @param id the value for t_sys_code_set.ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.MODEL_CODE
     *
     * @return the value of t_sys_code_set.MODEL_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getModelCode() {
        return modelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.MODEL_CODE
     *
     * @param modelCode the value for t_sys_code_set.MODEL_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setModelCode(String modelCode) {
        this.modelCode = modelCode == null ? null : modelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.SET_CODE
     *
     * @return the value of t_sys_code_set.SET_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getSetCode() {
        return setCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.SET_CODE
     *
     * @param setCode the value for t_sys_code_set.SET_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setSetCode(String setCode) {
        this.setCode = setCode == null ? null : setCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.SET_NAME
     *
     * @return the value of t_sys_code_set.SET_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getSetName() {
        return setName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.SET_NAME
     *
     * @param setName the value for t_sys_code_set.SET_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setSetName(String setName) {
        this.setName = setName == null ? null : setName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.ITEM_CODE
     *
     * @return the value of t_sys_code_set.ITEM_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.ITEM_CODE
     *
     * @param itemCode the value for t_sys_code_set.ITEM_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.ITEM_NAME
     *
     * @return the value of t_sys_code_set.ITEM_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.ITEM_NAME
     *
     * @param itemName the value for t_sys_code_set.ITEM_NAME
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.ITEM_SORT
     *
     * @return the value of t_sys_code_set.ITEM_SORT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Integer getItemSort() {
        return itemSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.ITEM_SORT
     *
     * @param itemSort the value for t_sys_code_set.ITEM_SORT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setItemSort(Integer itemSort) {
        this.itemSort = itemSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.ITEM_PARENT
     *
     * @return the value of t_sys_code_set.ITEM_PARENT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getItemParent() {
        return itemParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.ITEM_PARENT
     *
     * @param itemParent the value for t_sys_code_set.ITEM_PARENT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setItemParent(String itemParent) {
        this.itemParent = itemParent == null ? null : itemParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.ITEM_RELATION
     *
     * @return the value of t_sys_code_set.ITEM_RELATION
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getItemRelation() {
        return itemRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.ITEM_RELATION
     *
     * @param itemRelation the value for t_sys_code_set.ITEM_RELATION
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setItemRelation(String itemRelation) {
        this.itemRelation = itemRelation == null ? null : itemRelation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.IS_EDIT
     *
     * @return the value of t_sys_code_set.IS_EDIT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getIsEdit() {
        return isEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.IS_EDIT
     *
     * @param isEdit the value for t_sys_code_set.IS_EDIT
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setIsEdit(String isEdit) {
        this.isEdit = isEdit == null ? null : isEdit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.PLAT_CODE
     *
     * @return the value of t_sys_code_set.PLAT_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getPlatCode() {
        return platCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.PLAT_CODE
     *
     * @param platCode the value for t_sys_code_set.PLAT_CODE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setPlatCode(String platCode) {
        this.platCode = platCode == null ? null : platCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.ITEM_DESC
     *
     * @return the value of t_sys_code_set.ITEM_DESC
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.ITEM_DESC
     *
     * @param itemDesc the value for t_sys_code_set.ITEM_DESC
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc == null ? null : itemDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.ITEM_LEVEL
     *
     * @return the value of t_sys_code_set.ITEM_LEVEL
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Integer getItemLevel() {
        return itemLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.ITEM_LEVEL
     *
     * @param itemLevel the value for t_sys_code_set.ITEM_LEVEL
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setItemLevel(Integer itemLevel) {
        this.itemLevel = itemLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.REMARK
     *
     * @return the value of t_sys_code_set.REMARK
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.REMARK
     *
     * @param remark the value for t_sys_code_set.REMARK
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.STATUS
     *
     * @return the value of t_sys_code_set.STATUS
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.STATUS
     *
     * @param status the value for t_sys_code_set.STATUS
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.CREATE_USER
     *
     * @return the value of t_sys_code_set.CREATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.CREATE_USER
     *
     * @param createUser the value for t_sys_code_set.CREATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.CREATE_DATE
     *
     * @return the value of t_sys_code_set.CREATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.CREATE_DATE
     *
     * @param createDate the value for t_sys_code_set.CREATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.UPDATE_USER
     *
     * @return the value of t_sys_code_set.UPDATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.UPDATE_USER
     *
     * @param updateUser the value for t_sys_code_set.UPDATE_USER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.UPDATE_DATE
     *
     * @return the value of t_sys_code_set.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.UPDATE_DATE
     *
     * @param updateDate the value for t_sys_code_set.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.ALIVE_FLAG
     *
     * @return the value of t_sys_code_set.ALIVE_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getAliveFlag() {
        return aliveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.ALIVE_FLAG
     *
     * @param aliveFlag the value for t_sys_code_set.ALIVE_FLAG
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setAliveFlag(String aliveFlag) {
        this.aliveFlag = aliveFlag == null ? null : aliveFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.MARKET_ID
     *
     * @return the value of t_sys_code_set.MARKET_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getMarketId() {
        return marketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.MARKET_ID
     *
     * @param marketId the value for t_sys_code_set.MARKET_ID
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setMarketId(String marketId) {
        this.marketId = marketId == null ? null : marketId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.LANG_VER
     *
     * @return the value of t_sys_code_set.LANG_VER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getLangVer() {
        return langVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.LANG_VER
     *
     * @param langVer the value for t_sys_code_set.LANG_VER
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setLangVer(String langVer) {
        this.langVer = langVer == null ? null : langVer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.EXT1
     *
     * @return the value of t_sys_code_set.EXT1
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.EXT1
     *
     * @param ext1 the value for t_sys_code_set.EXT1
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.EXT2
     *
     * @return the value of t_sys_code_set.EXT2
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.EXT2
     *
     * @param ext2 the value for t_sys_code_set.EXT2
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.EXT3
     *
     * @return the value of t_sys_code_set.EXT3
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.EXT3
     *
     * @param ext3 the value for t_sys_code_set.EXT3
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.EXT4
     *
     * @return the value of t_sys_code_set.EXT4
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.EXT4
     *
     * @param ext4 the value for t_sys_code_set.EXT4
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.EXT5
     *
     * @return the value of t_sys_code_set.EXT5
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.EXT5
     *
     * @param ext5 the value for t_sys_code_set.EXT5
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.EXT6
     *
     * @return the value of t_sys_code_set.EXT6
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExt6() {
        return ext6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.EXT6
     *
     * @param ext6 the value for t_sys_code_set.EXT6
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExt6(String ext6) {
        this.ext6 = ext6 == null ? null : ext6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.EXT7
     *
     * @return the value of t_sys_code_set.EXT7
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExt7() {
        return ext7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.EXT7
     *
     * @param ext7 the value for t_sys_code_set.EXT7
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExt7(String ext7) {
        this.ext7 = ext7 == null ? null : ext7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.EXT8
     *
     * @return the value of t_sys_code_set.EXT8
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExt8() {
        return ext8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.EXT8
     *
     * @param ext8 the value for t_sys_code_set.EXT8
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExt8(String ext8) {
        this.ext8 = ext8 == null ? null : ext8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.EXT9
     *
     * @return the value of t_sys_code_set.EXT9
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExt9() {
        return ext9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.EXT9
     *
     * @param ext9 the value for t_sys_code_set.EXT9
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExt9(String ext9) {
        this.ext9 = ext9 == null ? null : ext9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code_set.EXT10
     *
     * @return the value of t_sys_code_set.EXT10
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public String getExt10() {
        return ext10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code_set.EXT10
     *
     * @param ext10 the value for t_sys_code_set.EXT10
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    public void setExt10(String ext10) {
        this.ext10 = ext10 == null ? null : ext10.trim();
    }
}