
feignUrl: https://transaction9.myoilbank.com
parter: shipagent
apikey: 670ae10a2c87dcd1be94c68602463d0d
userDomin: https://user9.myoilbank.com
hystrix.command.default.execution.timeout.enabled: false

#log
logging:
config: classpath:logback.xml

#aes 加解密
aeskey: "sinochemOILBANK1"
useaes: "true1"