package com.sinochem.crude.trade.productOil.dao;

import com.sinochem.crude.trade.productOil.model.TCmsInfoContent;

public interface TCmsInfoContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_info_content
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_info_content
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    int insert(TCmsInfoContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_info_content
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    int insertSelective(TCmsInfoContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_info_content
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    TCmsInfoContent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_info_content
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    int updateByPrimaryKeySelective(TCmsInfoContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_info_content
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(TCmsInfoContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_info_content
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    int updateByPrimaryKey(TCmsInfoContent record);
    
    /**
     * 根据咨询Id查询内容
     * @param infoId
     * @return
     * 2018年3月23日
     */
    TCmsInfoContent selectByInfoId(Long infoId);
}