package com.sinochem.crude.trade.productOil.dao;


import com.sinochem.crude.trade.productOil.model.TCmsChannelSub;

public interface TCmsChannelSubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_channel_sub
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_channel_sub
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    int insert(TCmsChannelSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_channel_sub
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    int insertSelective(TCmsChannelSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_channel_sub
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    TCmsChannelSub selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_channel_sub
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    int updateByPrimaryKeySelective(TCmsChannelSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_channel_sub
     *
     * @mbggenerated Thu Mar 22 14:11:25 CST 2018
     */
    int updateByPrimaryKey(TCmsChannelSub record);
    
    /**
     * 根据频道代码查询频道信息
     * @param channelCode
     * @return
     * 2018年3月22日
     */
    TCmsChannelSub selectByChannelCode(String channelCode);
    
    
    
}