package com.sinochem.crude.trade.listed.domain;

import java.util.Date;

/**
 * 与贸易链与member的中间表交互的domain
 * Made By WangTing
 */
public class TradingChainMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.trading_chain_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long tradingChainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.member_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.enterprise_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.serial_number
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Integer serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.role_type
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private String roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.operation_status
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private String operationStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.accept_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Date acceptTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.reject_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Date rejectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.remark
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.uuid
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.create_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.alter_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Date alterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.user_created
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long userCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.user_modified
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long userModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.alive_flag
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long aliveFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_member.version
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.id
     *
     * @return the value of trading_chain_member.id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.id
     *
     * @param id the value for trading_chain_member.id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.trading_chain_id
     *
     * @return the value of trading_chain_member.trading_chain_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getTradingChainId() {
        return tradingChainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.trading_chain_id
     *
     * @param tradingChainId the value for trading_chain_member.trading_chain_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setTradingChainId(Long tradingChainId) {
        this.tradingChainId = tradingChainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.member_id
     *
     * @return the value of trading_chain_member.member_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.member_id
     *
     * @param memberId the value for trading_chain_member.member_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.enterprise_id
     *
     * @return the value of trading_chain_member.enterprise_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.enterprise_id
     *
     * @param enterpriseId the value for trading_chain_member.enterprise_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.serial_number
     *
     * @return the value of trading_chain_member.serial_number
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Integer getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.serial_number
     *
     * @param serialNumber the value for trading_chain_member.serial_number
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setSerialNumber(Integer serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.role_type
     *
     * @return the value of trading_chain_member.role_type
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.role_type
     *
     * @param roleType the value for trading_chain_member.role_type
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.operation_status
     *
     * @return the value of trading_chain_member.operation_status
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public String getOperationStatus() {
        return operationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.operation_status
     *
     * @param operationStatus the value for trading_chain_member.operation_status
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setOperationStatus(String operationStatus) {
        this.operationStatus = operationStatus == null ? null : operationStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.accept_time
     *
     * @return the value of trading_chain_member.accept_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Date getAcceptTime() {
        return acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.accept_time
     *
     * @param acceptTime the value for trading_chain_member.accept_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setAcceptTime(Date acceptTime) {
        this.acceptTime = acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.reject_time
     *
     * @return the value of trading_chain_member.reject_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Date getRejectTime() {
        return rejectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.reject_time
     *
     * @param rejectTime the value for trading_chain_member.reject_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setRejectTime(Date rejectTime) {
        this.rejectTime = rejectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.remark
     *
     * @return the value of trading_chain_member.remark
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.remark
     *
     * @param remark the value for trading_chain_member.remark
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.uuid
     *
     * @return the value of trading_chain_member.uuid
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.uuid
     *
     * @param uuid the value for trading_chain_member.uuid
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.create_time
     *
     * @return the value of trading_chain_member.create_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.create_time
     *
     * @param createTime the value for trading_chain_member.create_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.alter_time
     *
     * @return the value of trading_chain_member.alter_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Date getAlterTime() {
        return alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.alter_time
     *
     * @param alterTime the value for trading_chain_member.alter_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setAlterTime(Date alterTime) {
        this.alterTime = alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.user_created
     *
     * @return the value of trading_chain_member.user_created
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getUserCreated() {
        return userCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.user_created
     *
     * @param userCreated the value for trading_chain_member.user_created
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setUserCreated(Long userCreated) {
        this.userCreated = userCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.user_modified
     *
     * @return the value of trading_chain_member.user_modified
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getUserModified() {
        return userModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.user_modified
     *
     * @param userModified the value for trading_chain_member.user_modified
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setUserModified(Long userModified) {
        this.userModified = userModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.alive_flag
     *
     * @return the value of trading_chain_member.alive_flag
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getAliveFlag() {
        return aliveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.alive_flag
     *
     * @param aliveFlag the value for trading_chain_member.alive_flag
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setAliveFlag(Long aliveFlag) {
        this.aliveFlag = aliveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_member.version
     *
     * @return the value of trading_chain_member.version
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_member.version
     *
     * @param version the value for trading_chain_member.version
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}