package com.sinochem.crude.trade.listed.domain;

import java.util.Date;

/**
 * 与贸易链与demand的中间表交互的domain
 * Made By WangTing
 */
public class TradingChainDemand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_demand.id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_demand.trading_chain_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long tradingChainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_demand.demand_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long demandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_demand.serial_number
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Integer serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_demand.uuid
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_demand.create_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_demand.alter_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Date alterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_demand.user_created
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long userCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_demand.user_modified
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long userModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_demand.alive_flag
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long aliveFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_chain_demand.version
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    private Long version;

    /**
     * 生成的订单编号
     */
    private String orderNo;

    /**
     * 生成的订单uuid
     */
    private String orderUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_demand.id
     *
     * @return the value of trading_chain_demand.id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_demand.id
     *
     * @param id the value for trading_chain_demand.id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_demand.trading_chain_id
     *
     * @return the value of trading_chain_demand.trading_chain_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getTradingChainId() {
        return tradingChainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_demand.trading_chain_id
     *
     * @param tradingChainId the value for trading_chain_demand.trading_chain_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setTradingChainId(Long tradingChainId) {
        this.tradingChainId = tradingChainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_demand.demand_id
     *
     * @return the value of trading_chain_demand.demand_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getDemandId() {
        return demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_demand.demand_id
     *
     * @param demandId the value for trading_chain_demand.demand_id
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setDemandId(Long demandId) {
        this.demandId = demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_demand.serial_number
     *
     * @return the value of trading_chain_demand.serial_number
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Integer getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_demand.serial_number
     *
     * @param serialNumber the value for trading_chain_demand.serial_number
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setSerialNumber(Integer serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_demand.uuid
     *
     * @return the value of trading_chain_demand.uuid
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_demand.uuid
     *
     * @param uuid the value for trading_chain_demand.uuid
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_demand.create_time
     *
     * @return the value of trading_chain_demand.create_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_demand.create_time
     *
     * @param createTime the value for trading_chain_demand.create_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_demand.alter_time
     *
     * @return the value of trading_chain_demand.alter_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Date getAlterTime() {
        return alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_demand.alter_time
     *
     * @param alterTime the value for trading_chain_demand.alter_time
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setAlterTime(Date alterTime) {
        this.alterTime = alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_demand.user_created
     *
     * @return the value of trading_chain_demand.user_created
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getUserCreated() {
        return userCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_demand.user_created
     *
     * @param userCreated the value for trading_chain_demand.user_created
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setUserCreated(Long userCreated) {
        this.userCreated = userCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_demand.user_modified
     *
     * @return the value of trading_chain_demand.user_modified
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getUserModified() {
        return userModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_demand.user_modified
     *
     * @param userModified the value for trading_chain_demand.user_modified
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setUserModified(Long userModified) {
        this.userModified = userModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_demand.alive_flag
     *
     * @return the value of trading_chain_demand.alive_flag
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getAliveFlag() {
        return aliveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_demand.alive_flag
     *
     * @param aliveFlag the value for trading_chain_demand.alive_flag
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setAliveFlag(Long aliveFlag) {
        this.aliveFlag = aliveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_chain_demand.version
     *
     * @return the value of trading_chain_demand.version
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_chain_demand.version
     *
     * @param version the value for trading_chain_demand.version
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getOrderUuid() {
        return orderUuid;
    }

    public void setOrderUuid(String orderUuid) {
        this.orderUuid = orderUuid;
    }
}