#api
feignUrl: http://127.0.0.1/t
parter: customs
apikey: ad846cd10b74d0d11443fcf0be2de2eb
hystrix.command.default.execution.timeout.enabled: false
userDomin: http://www.sinochem.com
#log
logging:
config: classpath:logback.xml

#aes 加解密
aeskey: "sinochemOILBANK1"
useaes: "true1"