#api
feignUrl: https://transaction9.myoilbank.com
parter: customs
apikey: ad846cd10b74d0d11443fcf0be2de2eb
userDomin: https://user9.myoilbank.com
#log
logging:
config: classpath:logback.xml

#aes 加解密
aeskey: "sinochemOILBANK1"
useaes: "true1"