package com.sinochem.crude.trade.listed.dao;


import com.sinochem.crude.trade.listed.domain.TradingChainMember;

import java.util.List;

public interface TradingChainMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_chain_member
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_chain_member
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    int insert(TradingChainMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_chain_member
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    int insertSelective(TradingChainMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_chain_member
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    TradingChainMember selectByPrimaryKey(Long id);


    TradingChainMember selectByUuid(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_chain_member
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    int updateByPrimaryKeySelective(TradingChainMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_chain_member
     *
     * @mbggenerated Thu Apr 12 19:31:55 CST 2018
     */
    int updateByPrimaryKey(TradingChainMember record);

    /**
     * 根据贸易链表id查询所有与本条贸易链相关的企业记录
     */
    List<TradingChainMember> selectByTradingChainId(Long tradingChainId);
}