package com.sinochem.crude.trade.wechat.dao;
import com.sinochem.crude.trade.wechat.domain.WechatLogs;

import java.util.List;


public interface WechatLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_logs
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_logs
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    int insert(WechatLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_logs
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    int insertSelective(WechatLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_logs
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    WechatLogs selectByPrimaryKey(Integer id);

    List<WechatLogs> selectall(int start, int end);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_logs
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    int updateByPrimaryKeySelective(WechatLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_logs
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(WechatLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_logs
     *
     * @mbggenerated Tue Apr 10 19:22:58 CST 2018
     */
    int updateByPrimaryKey(WechatLogs record);
}