package com.sinochem.crude.trade.wechat.dao;

import com.sinochem.crude.trade.wechat.domain.WechatSendmsgLogs;

import java.util.List;

public interface WechatSendmsgLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_sendmsg_logs
     *
     * @mbggenerated Sat Apr 14 09:43:47 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    List<WechatSendmsgLogs> selectall(int start, int end);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_sendmsg_logs
     *
     * @mbggenerated Sat Apr 14 09:43:47 CST 2018
     */
    int insert(WechatSendmsgLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_sendmsg_logs
     *
     * @mbggenerated Sat Apr 14 09:43:47 CST 2018
     */
    int insertSelective(WechatSendmsgLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_sendmsg_logs
     *
     * @mbggenerated Sat Apr 14 09:43:47 CST 2018
     */
    WechatSendmsgLogs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_sendmsg_logs
     *
     * @mbggenerated Sat Apr 14 09:43:47 CST 2018
     */
    int updateByPrimaryKeySelective(WechatSendmsgLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_sendmsg_logs
     *
     * @mbggenerated Sat Apr 14 09:43:47 CST 2018
     */
    int updateByPrimaryKey(WechatSendmsgLogs record);
}