package com.sinochem.crude.trade.order.domain;

import java.util.Date;

public class ContractLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_log.id
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_log.contract_id
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    private Long contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_log.operation_type
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    private String operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_log.describes
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    private String describes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_log.oper_name
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    private String operName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_log.creater
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    private Long creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_log.create_time
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_log.id
     *
     * @return the value of contract_log.id
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_log.id
     *
     * @param id the value for contract_log.id
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_log.contract_id
     *
     * @return the value of contract_log.contract_id
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public Long getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_log.contract_id
     *
     * @param contractId the value for contract_log.contract_id
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_log.operation_type
     *
     * @return the value of contract_log.operation_type
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_log.operation_type
     *
     * @param operationType the value for contract_log.operation_type
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_log.describes
     *
     * @return the value of contract_log.describes
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public String getDescribes() {
        return describes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_log.describes
     *
     * @param describes the value for contract_log.describes
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public void setDescribes(String describes) {
        this.describes = describes == null ? null : describes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_log.oper_name
     *
     * @return the value of contract_log.oper_name
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public String getOperName() {
        return operName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_log.oper_name
     *
     * @param operName the value for contract_log.oper_name
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public void setOperName(String operName) {
        this.operName = operName == null ? null : operName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_log.creater
     *
     * @return the value of contract_log.creater
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public Long getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_log.creater
     *
     * @param creater the value for contract_log.creater
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_log.create_time
     *
     * @return the value of contract_log.create_time
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_log.create_time
     *
     * @param createTime the value for contract_log.create_time
     *
     * @mbggenerated Wed Feb 28 21:02:27 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}