package com.sinochem.crude.trade.broker.domain;

public class TBrokerOthermatters {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_othermatters.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_othermatters.declarationuuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String declarationuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_othermatters.type
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_othermatters.value
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private Integer value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_othermatters.id
     *
     * @return the value of t_broker_othermatters.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_othermatters.id
     *
     * @param id the value for t_broker_othermatters.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_othermatters.declarationuuid
     *
     * @return the value of t_broker_othermatters.declarationuuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getDeclarationuuid() {
        return declarationuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_othermatters.declarationuuid
     *
     * @param declarationuuid the value for t_broker_othermatters.declarationuuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setDeclarationuuid(String declarationuuid) {
        this.declarationuuid = declarationuuid == null ? null : declarationuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_othermatters.type
     *
     * @return the value of t_broker_othermatters.type
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_othermatters.type
     *
     * @param type the value for t_broker_othermatters.type
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_othermatters.value
     *
     * @return the value of t_broker_othermatters.value
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_othermatters.value
     *
     * @param value the value for t_broker_othermatters.value
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setValue(Integer value) {
        this.value = value;
    }
}