package com.sinochem.crude.trade.broker.domain;

public class TBrokerBusinessmatters {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_businessmatters.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_businessmatters.declarationuuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String declarationuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_businessmatters.businesscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String businesscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_businessmatters.businessname
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String businessname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_businessmatters.id
     *
     * @return the value of t_broker_businessmatters.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_businessmatters.id
     *
     * @param id the value for t_broker_businessmatters.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_businessmatters.declarationuuid
     *
     * @return the value of t_broker_businessmatters.declarationuuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getDeclarationuuid() {
        return declarationuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_businessmatters.declarationuuid
     *
     * @param declarationuuid the value for t_broker_businessmatters.declarationuuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setDeclarationuuid(String declarationuuid) {
        this.declarationuuid = declarationuuid == null ? null : declarationuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_businessmatters.businesscode
     *
     * @return the value of t_broker_businessmatters.businesscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getBusinesscode() {
        return businesscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_businessmatters.businesscode
     *
     * @param businesscode the value for t_broker_businessmatters.businesscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setBusinesscode(String businesscode) {
        this.businesscode = businesscode == null ? null : businesscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_businessmatters.businessname
     *
     * @return the value of t_broker_businessmatters.businessname
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getBusinessname() {
        return businessname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_businessmatters.businessname
     *
     * @param businessname the value for t_broker_businessmatters.businessname
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setBusinessname(String businessname) {
        this.businessname = businessname == null ? null : businessname.trim();
    }
}