package com.sinochem.crude.trade.broker.domain;

public class TBrokerOtherpackinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_otherpackinfo.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_otherpackinfo.declarationuuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String declarationuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_otherpackinfo.packtypecode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String packtypecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_otherpackinfo.id
     *
     * @return the value of t_broker_otherpackinfo.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_otherpackinfo.id
     *
     * @param id the value for t_broker_otherpackinfo.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_otherpackinfo.declarationuuid
     *
     * @return the value of t_broker_otherpackinfo.declarationuuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getDeclarationuuid() {
        return declarationuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_otherpackinfo.declarationuuid
     *
     * @param declarationuuid the value for t_broker_otherpackinfo.declarationuuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setDeclarationuuid(String declarationuuid) {
        this.declarationuuid = declarationuuid == null ? null : declarationuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_otherpackinfo.packtypecode
     *
     * @return the value of t_broker_otherpackinfo.packtypecode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getPacktypecode() {
        return packtypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_otherpackinfo.packtypecode
     *
     * @param packtypecode the value for t_broker_otherpackinfo.packtypecode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setPacktypecode(String packtypecode) {
        this.packtypecode = packtypecode == null ? null : packtypecode.trim();
    }
}