package com.sinochem.crude.trade.broker.domain;

public class TBrokerDangerinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_dangerinfo.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_dangerinfo.declarationuuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String declarationuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_dangerinfo.uncode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String uncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_dangerinfo.goodsname
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String goodsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_dangerinfo.dangerouschemicals
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String dangerouschemicals;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_dangerinfo.id
     *
     * @return the value of t_broker_dangerinfo.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_dangerinfo.id
     *
     * @param id the value for t_broker_dangerinfo.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_dangerinfo.declarationuuid
     *
     * @return the value of t_broker_dangerinfo.declarationuuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getDeclarationuuid() {
        return declarationuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_dangerinfo.declarationuuid
     *
     * @param declarationuuid the value for t_broker_dangerinfo.declarationuuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setDeclarationuuid(String declarationuuid) {
        this.declarationuuid = declarationuuid == null ? null : declarationuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_dangerinfo.uncode
     *
     * @return the value of t_broker_dangerinfo.uncode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getUncode() {
        return uncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_dangerinfo.uncode
     *
     * @param uncode the value for t_broker_dangerinfo.uncode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setUncode(String uncode) {
        this.uncode = uncode == null ? null : uncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_dangerinfo.goodsname
     *
     * @return the value of t_broker_dangerinfo.goodsname
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_dangerinfo.goodsname
     *
     * @param goodsname the value for t_broker_dangerinfo.goodsname
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_dangerinfo.dangerouschemicals
     *
     * @return the value of t_broker_dangerinfo.dangerouschemicals
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getDangerouschemicals() {
        return dangerouschemicals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_dangerinfo.dangerouschemicals
     *
     * @param dangerouschemicals the value for t_broker_dangerinfo.dangerouschemicals
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setDangerouschemicals(String dangerouschemicals) {
        this.dangerouschemicals = dangerouschemicals == null ? null : dangerouschemicals.trim();
    }
}