package com.sinochem.crude.trade.broker.domain;

import java.math.BigDecimal;
import java.util.Date;

public class TBrokerDeclaration {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.enterprise_id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private Long enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.status
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.unifiedcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String unifiedcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.purchase_contract_no
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String purchaseContractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.inseastradeco
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String inseastradeco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.overseastradeco
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String overseastradeco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.enterprisename_ch
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String enterprisenameCh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.enterprisename_en
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String enterprisenameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.checkoutno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String checkoutno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.declare_creditcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String declareCreditcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.declare_customscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String declareCustomscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.declare_checkoutno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String declareCheckoutno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.declare_enterprisename
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String declareEnterprisename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.production_creditcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String productionCreditcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.production_customscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String productionCustomscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.production_checkoutno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String productionCheckoutno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.production_enterprisename
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String productionEnterprisename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_customscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoCustomscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_ieportcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoIeportcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_trafmode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoTrafmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_voyno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoVoyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_distinateport
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoDistinateport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_nativeshipname
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoNativeshipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_deliveryno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoDeliveryno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_trademode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoTrademode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_cutmode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoCutmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_transmode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoTransmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_licenseno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoLicenseno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_tradecountry
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoTradecountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_packqty
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private BigDecimal customsinfoPackqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_packtype
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoPacktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_grosswt
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private BigDecimal customsinfoGrosswt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_netwt
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private BigDecimal customsinfoNetwt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_entyportcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoEntyportcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_entrytype
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoEntrytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_tradeareacode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoTradeareacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_goodsplace
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoGoodsplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_vsaorgcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoVsaorgcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_orgcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoOrgcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_insporgcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoInsporgcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.customsinfo_note
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String customsinfoNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_decgno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String goodsinfoDecgno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_priceperunit
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private BigDecimal goodsinfoPriceperunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_decltotal
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private BigDecimal goodsinfoDecltotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_gqty
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private BigDecimal goodsinfoGqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_gunit
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String goodsinfoGunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_cutmode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String goodsinfoCutmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_tradecurr
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String goodsinfoTradecurr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_codets
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String goodsinfoCodets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_gname
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String goodsinfoGname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_qty1
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private BigDecimal goodsinfoQty1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_qty2
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private BigDecimal goodsinfoQty2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_destinationcountry
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String goodsinfoDestinationcountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_origincountry
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String goodsinfoOrigincountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.goodsinfo_districtcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String goodsinfoDistrictcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.contactperson
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String contactperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.contactway
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String contactway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.uuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_broker_declaration.createtime
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.id
     *
     * @return the value of t_broker_declaration.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.id
     *
     * @param id the value for t_broker_declaration.id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.enterprise_id
     *
     * @return the value of t_broker_declaration.enterprise_id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public Long getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.enterprise_id
     *
     * @param enterpriseId the value for t_broker_declaration.enterprise_id
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.status
     *
     * @return the value of t_broker_declaration.status
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.status
     *
     * @param status the value for t_broker_declaration.status
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.unifiedcode
     *
     * @return the value of t_broker_declaration.unifiedcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getUnifiedcode() {
        return unifiedcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.unifiedcode
     *
     * @param unifiedcode the value for t_broker_declaration.unifiedcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setUnifiedcode(String unifiedcode) {
        this.unifiedcode = unifiedcode == null ? null : unifiedcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.purchase_contract_no
     *
     * @return the value of t_broker_declaration.purchase_contract_no
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getPurchaseContractNo() {
        return purchaseContractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.purchase_contract_no
     *
     * @param purchaseContractNo the value for t_broker_declaration.purchase_contract_no
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setPurchaseContractNo(String purchaseContractNo) {
        this.purchaseContractNo = purchaseContractNo == null ? null : purchaseContractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.inseastradeco
     *
     * @return the value of t_broker_declaration.inseastradeco
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getInseastradeco() {
        return inseastradeco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.inseastradeco
     *
     * @param inseastradeco the value for t_broker_declaration.inseastradeco
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setInseastradeco(String inseastradeco) {
        this.inseastradeco = inseastradeco == null ? null : inseastradeco.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.overseastradeco
     *
     * @return the value of t_broker_declaration.overseastradeco
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getOverseastradeco() {
        return overseastradeco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.overseastradeco
     *
     * @param overseastradeco the value for t_broker_declaration.overseastradeco
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setOverseastradeco(String overseastradeco) {
        this.overseastradeco = overseastradeco == null ? null : overseastradeco.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.enterprisename_ch
     *
     * @return the value of t_broker_declaration.enterprisename_ch
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getEnterprisenameCh() {
        return enterprisenameCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.enterprisename_ch
     *
     * @param enterprisenameCh the value for t_broker_declaration.enterprisename_ch
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setEnterprisenameCh(String enterprisenameCh) {
        this.enterprisenameCh = enterprisenameCh == null ? null : enterprisenameCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.enterprisename_en
     *
     * @return the value of t_broker_declaration.enterprisename_en
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getEnterprisenameEn() {
        return enterprisenameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.enterprisename_en
     *
     * @param enterprisenameEn the value for t_broker_declaration.enterprisename_en
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setEnterprisenameEn(String enterprisenameEn) {
        this.enterprisenameEn = enterprisenameEn == null ? null : enterprisenameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.checkoutno
     *
     * @return the value of t_broker_declaration.checkoutno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCheckoutno() {
        return checkoutno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.checkoutno
     *
     * @param checkoutno the value for t_broker_declaration.checkoutno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCheckoutno(String checkoutno) {
        this.checkoutno = checkoutno == null ? null : checkoutno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customscode
     *
     * @return the value of t_broker_declaration.customscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomscode() {
        return customscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customscode
     *
     * @param customscode the value for t_broker_declaration.customscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomscode(String customscode) {
        this.customscode = customscode == null ? null : customscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.declare_creditcode
     *
     * @return the value of t_broker_declaration.declare_creditcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getDeclareCreditcode() {
        return declareCreditcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.declare_creditcode
     *
     * @param declareCreditcode the value for t_broker_declaration.declare_creditcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setDeclareCreditcode(String declareCreditcode) {
        this.declareCreditcode = declareCreditcode == null ? null : declareCreditcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.declare_customscode
     *
     * @return the value of t_broker_declaration.declare_customscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getDeclareCustomscode() {
        return declareCustomscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.declare_customscode
     *
     * @param declareCustomscode the value for t_broker_declaration.declare_customscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setDeclareCustomscode(String declareCustomscode) {
        this.declareCustomscode = declareCustomscode == null ? null : declareCustomscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.declare_checkoutno
     *
     * @return the value of t_broker_declaration.declare_checkoutno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getDeclareCheckoutno() {
        return declareCheckoutno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.declare_checkoutno
     *
     * @param declareCheckoutno the value for t_broker_declaration.declare_checkoutno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setDeclareCheckoutno(String declareCheckoutno) {
        this.declareCheckoutno = declareCheckoutno == null ? null : declareCheckoutno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.declare_enterprisename
     *
     * @return the value of t_broker_declaration.declare_enterprisename
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getDeclareEnterprisename() {
        return declareEnterprisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.declare_enterprisename
     *
     * @param declareEnterprisename the value for t_broker_declaration.declare_enterprisename
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setDeclareEnterprisename(String declareEnterprisename) {
        this.declareEnterprisename = declareEnterprisename == null ? null : declareEnterprisename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.production_creditcode
     *
     * @return the value of t_broker_declaration.production_creditcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getProductionCreditcode() {
        return productionCreditcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.production_creditcode
     *
     * @param productionCreditcode the value for t_broker_declaration.production_creditcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setProductionCreditcode(String productionCreditcode) {
        this.productionCreditcode = productionCreditcode == null ? null : productionCreditcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.production_customscode
     *
     * @return the value of t_broker_declaration.production_customscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getProductionCustomscode() {
        return productionCustomscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.production_customscode
     *
     * @param productionCustomscode the value for t_broker_declaration.production_customscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setProductionCustomscode(String productionCustomscode) {
        this.productionCustomscode = productionCustomscode == null ? null : productionCustomscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.production_checkoutno
     *
     * @return the value of t_broker_declaration.production_checkoutno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getProductionCheckoutno() {
        return productionCheckoutno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.production_checkoutno
     *
     * @param productionCheckoutno the value for t_broker_declaration.production_checkoutno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setProductionCheckoutno(String productionCheckoutno) {
        this.productionCheckoutno = productionCheckoutno == null ? null : productionCheckoutno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.production_enterprisename
     *
     * @return the value of t_broker_declaration.production_enterprisename
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getProductionEnterprisename() {
        return productionEnterprisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.production_enterprisename
     *
     * @param productionEnterprisename the value for t_broker_declaration.production_enterprisename
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setProductionEnterprisename(String productionEnterprisename) {
        this.productionEnterprisename = productionEnterprisename == null ? null : productionEnterprisename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_customscode
     *
     * @return the value of t_broker_declaration.customsinfo_customscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoCustomscode() {
        return customsinfoCustomscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_customscode
     *
     * @param customsinfoCustomscode the value for t_broker_declaration.customsinfo_customscode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoCustomscode(String customsinfoCustomscode) {
        this.customsinfoCustomscode = customsinfoCustomscode == null ? null : customsinfoCustomscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_ieportcode
     *
     * @return the value of t_broker_declaration.customsinfo_ieportcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoIeportcode() {
        return customsinfoIeportcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_ieportcode
     *
     * @param customsinfoIeportcode the value for t_broker_declaration.customsinfo_ieportcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoIeportcode(String customsinfoIeportcode) {
        this.customsinfoIeportcode = customsinfoIeportcode == null ? null : customsinfoIeportcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_trafmode
     *
     * @return the value of t_broker_declaration.customsinfo_trafmode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoTrafmode() {
        return customsinfoTrafmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_trafmode
     *
     * @param customsinfoTrafmode the value for t_broker_declaration.customsinfo_trafmode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoTrafmode(String customsinfoTrafmode) {
        this.customsinfoTrafmode = customsinfoTrafmode == null ? null : customsinfoTrafmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_voyno
     *
     * @return the value of t_broker_declaration.customsinfo_voyno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoVoyno() {
        return customsinfoVoyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_voyno
     *
     * @param customsinfoVoyno the value for t_broker_declaration.customsinfo_voyno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoVoyno(String customsinfoVoyno) {
        this.customsinfoVoyno = customsinfoVoyno == null ? null : customsinfoVoyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_distinateport
     *
     * @return the value of t_broker_declaration.customsinfo_distinateport
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoDistinateport() {
        return customsinfoDistinateport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_distinateport
     *
     * @param customsinfoDistinateport the value for t_broker_declaration.customsinfo_distinateport
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoDistinateport(String customsinfoDistinateport) {
        this.customsinfoDistinateport = customsinfoDistinateport == null ? null : customsinfoDistinateport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_nativeshipname
     *
     * @return the value of t_broker_declaration.customsinfo_nativeshipname
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoNativeshipname() {
        return customsinfoNativeshipname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_nativeshipname
     *
     * @param customsinfoNativeshipname the value for t_broker_declaration.customsinfo_nativeshipname
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoNativeshipname(String customsinfoNativeshipname) {
        this.customsinfoNativeshipname = customsinfoNativeshipname == null ? null : customsinfoNativeshipname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_deliveryno
     *
     * @return the value of t_broker_declaration.customsinfo_deliveryno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoDeliveryno() {
        return customsinfoDeliveryno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_deliveryno
     *
     * @param customsinfoDeliveryno the value for t_broker_declaration.customsinfo_deliveryno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoDeliveryno(String customsinfoDeliveryno) {
        this.customsinfoDeliveryno = customsinfoDeliveryno == null ? null : customsinfoDeliveryno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_trademode
     *
     * @return the value of t_broker_declaration.customsinfo_trademode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoTrademode() {
        return customsinfoTrademode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_trademode
     *
     * @param customsinfoTrademode the value for t_broker_declaration.customsinfo_trademode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoTrademode(String customsinfoTrademode) {
        this.customsinfoTrademode = customsinfoTrademode == null ? null : customsinfoTrademode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_cutmode
     *
     * @return the value of t_broker_declaration.customsinfo_cutmode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoCutmode() {
        return customsinfoCutmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_cutmode
     *
     * @param customsinfoCutmode the value for t_broker_declaration.customsinfo_cutmode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoCutmode(String customsinfoCutmode) {
        this.customsinfoCutmode = customsinfoCutmode == null ? null : customsinfoCutmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_transmode
     *
     * @return the value of t_broker_declaration.customsinfo_transmode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoTransmode() {
        return customsinfoTransmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_transmode
     *
     * @param customsinfoTransmode the value for t_broker_declaration.customsinfo_transmode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoTransmode(String customsinfoTransmode) {
        this.customsinfoTransmode = customsinfoTransmode == null ? null : customsinfoTransmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_licenseno
     *
     * @return the value of t_broker_declaration.customsinfo_licenseno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoLicenseno() {
        return customsinfoLicenseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_licenseno
     *
     * @param customsinfoLicenseno the value for t_broker_declaration.customsinfo_licenseno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoLicenseno(String customsinfoLicenseno) {
        this.customsinfoLicenseno = customsinfoLicenseno == null ? null : customsinfoLicenseno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_tradecountry
     *
     * @return the value of t_broker_declaration.customsinfo_tradecountry
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoTradecountry() {
        return customsinfoTradecountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_tradecountry
     *
     * @param customsinfoTradecountry the value for t_broker_declaration.customsinfo_tradecountry
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoTradecountry(String customsinfoTradecountry) {
        this.customsinfoTradecountry = customsinfoTradecountry == null ? null : customsinfoTradecountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_packqty
     *
     * @return the value of t_broker_declaration.customsinfo_packqty
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public BigDecimal getCustomsinfoPackqty() {
        return customsinfoPackqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_packqty
     *
     * @param customsinfoPackqty the value for t_broker_declaration.customsinfo_packqty
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoPackqty(BigDecimal customsinfoPackqty) {
        this.customsinfoPackqty = customsinfoPackqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_packtype
     *
     * @return the value of t_broker_declaration.customsinfo_packtype
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoPacktype() {
        return customsinfoPacktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_packtype
     *
     * @param customsinfoPacktype the value for t_broker_declaration.customsinfo_packtype
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoPacktype(String customsinfoPacktype) {
        this.customsinfoPacktype = customsinfoPacktype == null ? null : customsinfoPacktype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_grosswt
     *
     * @return the value of t_broker_declaration.customsinfo_grosswt
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public BigDecimal getCustomsinfoGrosswt() {
        return customsinfoGrosswt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_grosswt
     *
     * @param customsinfoGrosswt the value for t_broker_declaration.customsinfo_grosswt
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoGrosswt(BigDecimal customsinfoGrosswt) {
        this.customsinfoGrosswt = customsinfoGrosswt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_netwt
     *
     * @return the value of t_broker_declaration.customsinfo_netwt
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public BigDecimal getCustomsinfoNetwt() {
        return customsinfoNetwt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_netwt
     *
     * @param customsinfoNetwt the value for t_broker_declaration.customsinfo_netwt
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoNetwt(BigDecimal customsinfoNetwt) {
        this.customsinfoNetwt = customsinfoNetwt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_entyportcode
     *
     * @return the value of t_broker_declaration.customsinfo_entyportcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoEntyportcode() {
        return customsinfoEntyportcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_entyportcode
     *
     * @param customsinfoEntyportcode the value for t_broker_declaration.customsinfo_entyportcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoEntyportcode(String customsinfoEntyportcode) {
        this.customsinfoEntyportcode = customsinfoEntyportcode == null ? null : customsinfoEntyportcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_entrytype
     *
     * @return the value of t_broker_declaration.customsinfo_entrytype
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoEntrytype() {
        return customsinfoEntrytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_entrytype
     *
     * @param customsinfoEntrytype the value for t_broker_declaration.customsinfo_entrytype
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoEntrytype(String customsinfoEntrytype) {
        this.customsinfoEntrytype = customsinfoEntrytype == null ? null : customsinfoEntrytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_tradeareacode
     *
     * @return the value of t_broker_declaration.customsinfo_tradeareacode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoTradeareacode() {
        return customsinfoTradeareacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_tradeareacode
     *
     * @param customsinfoTradeareacode the value for t_broker_declaration.customsinfo_tradeareacode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoTradeareacode(String customsinfoTradeareacode) {
        this.customsinfoTradeareacode = customsinfoTradeareacode == null ? null : customsinfoTradeareacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_goodsplace
     *
     * @return the value of t_broker_declaration.customsinfo_goodsplace
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoGoodsplace() {
        return customsinfoGoodsplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_goodsplace
     *
     * @param customsinfoGoodsplace the value for t_broker_declaration.customsinfo_goodsplace
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoGoodsplace(String customsinfoGoodsplace) {
        this.customsinfoGoodsplace = customsinfoGoodsplace == null ? null : customsinfoGoodsplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_vsaorgcode
     *
     * @return the value of t_broker_declaration.customsinfo_vsaorgcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoVsaorgcode() {
        return customsinfoVsaorgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_vsaorgcode
     *
     * @param customsinfoVsaorgcode the value for t_broker_declaration.customsinfo_vsaorgcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoVsaorgcode(String customsinfoVsaorgcode) {
        this.customsinfoVsaorgcode = customsinfoVsaorgcode == null ? null : customsinfoVsaorgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_orgcode
     *
     * @return the value of t_broker_declaration.customsinfo_orgcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoOrgcode() {
        return customsinfoOrgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_orgcode
     *
     * @param customsinfoOrgcode the value for t_broker_declaration.customsinfo_orgcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoOrgcode(String customsinfoOrgcode) {
        this.customsinfoOrgcode = customsinfoOrgcode == null ? null : customsinfoOrgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_insporgcode
     *
     * @return the value of t_broker_declaration.customsinfo_insporgcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoInsporgcode() {
        return customsinfoInsporgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_insporgcode
     *
     * @param customsinfoInsporgcode the value for t_broker_declaration.customsinfo_insporgcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoInsporgcode(String customsinfoInsporgcode) {
        this.customsinfoInsporgcode = customsinfoInsporgcode == null ? null : customsinfoInsporgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.customsinfo_note
     *
     * @return the value of t_broker_declaration.customsinfo_note
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getCustomsinfoNote() {
        return customsinfoNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.customsinfo_note
     *
     * @param customsinfoNote the value for t_broker_declaration.customsinfo_note
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCustomsinfoNote(String customsinfoNote) {
        this.customsinfoNote = customsinfoNote == null ? null : customsinfoNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_decgno
     *
     * @return the value of t_broker_declaration.goodsinfo_decgno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getGoodsinfoDecgno() {
        return goodsinfoDecgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_decgno
     *
     * @param goodsinfoDecgno the value for t_broker_declaration.goodsinfo_decgno
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoDecgno(String goodsinfoDecgno) {
        this.goodsinfoDecgno = goodsinfoDecgno == null ? null : goodsinfoDecgno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_priceperunit
     *
     * @return the value of t_broker_declaration.goodsinfo_priceperunit
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public BigDecimal getGoodsinfoPriceperunit() {
        return goodsinfoPriceperunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_priceperunit
     *
     * @param goodsinfoPriceperunit the value for t_broker_declaration.goodsinfo_priceperunit
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoPriceperunit(BigDecimal goodsinfoPriceperunit) {
        this.goodsinfoPriceperunit = goodsinfoPriceperunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_decltotal
     *
     * @return the value of t_broker_declaration.goodsinfo_decltotal
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public BigDecimal getGoodsinfoDecltotal() {
        return goodsinfoDecltotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_decltotal
     *
     * @param goodsinfoDecltotal the value for t_broker_declaration.goodsinfo_decltotal
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoDecltotal(BigDecimal goodsinfoDecltotal) {
        this.goodsinfoDecltotal = goodsinfoDecltotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_gqty
     *
     * @return the value of t_broker_declaration.goodsinfo_gqty
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public BigDecimal getGoodsinfoGqty() {
        return goodsinfoGqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_gqty
     *
     * @param goodsinfoGqty the value for t_broker_declaration.goodsinfo_gqty
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoGqty(BigDecimal goodsinfoGqty) {
        this.goodsinfoGqty = goodsinfoGqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_gunit
     *
     * @return the value of t_broker_declaration.goodsinfo_gunit
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getGoodsinfoGunit() {
        return goodsinfoGunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_gunit
     *
     * @param goodsinfoGunit the value for t_broker_declaration.goodsinfo_gunit
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoGunit(String goodsinfoGunit) {
        this.goodsinfoGunit = goodsinfoGunit == null ? null : goodsinfoGunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_cutmode
     *
     * @return the value of t_broker_declaration.goodsinfo_cutmode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getGoodsinfoCutmode() {
        return goodsinfoCutmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_cutmode
     *
     * @param goodsinfoCutmode the value for t_broker_declaration.goodsinfo_cutmode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoCutmode(String goodsinfoCutmode) {
        this.goodsinfoCutmode = goodsinfoCutmode == null ? null : goodsinfoCutmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_tradecurr
     *
     * @return the value of t_broker_declaration.goodsinfo_tradecurr
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getGoodsinfoTradecurr() {
        return goodsinfoTradecurr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_tradecurr
     *
     * @param goodsinfoTradecurr the value for t_broker_declaration.goodsinfo_tradecurr
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoTradecurr(String goodsinfoTradecurr) {
        this.goodsinfoTradecurr = goodsinfoTradecurr == null ? null : goodsinfoTradecurr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_codets
     *
     * @return the value of t_broker_declaration.goodsinfo_codets
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getGoodsinfoCodets() {
        return goodsinfoCodets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_codets
     *
     * @param goodsinfoCodets the value for t_broker_declaration.goodsinfo_codets
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoCodets(String goodsinfoCodets) {
        this.goodsinfoCodets = goodsinfoCodets == null ? null : goodsinfoCodets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_gname
     *
     * @return the value of t_broker_declaration.goodsinfo_gname
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getGoodsinfoGname() {
        return goodsinfoGname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_gname
     *
     * @param goodsinfoGname the value for t_broker_declaration.goodsinfo_gname
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoGname(String goodsinfoGname) {
        this.goodsinfoGname = goodsinfoGname == null ? null : goodsinfoGname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_qty1
     *
     * @return the value of t_broker_declaration.goodsinfo_qty1
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public BigDecimal getGoodsinfoQty1() {
        return goodsinfoQty1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_qty1
     *
     * @param goodsinfoQty1 the value for t_broker_declaration.goodsinfo_qty1
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoQty1(BigDecimal goodsinfoQty1) {
        this.goodsinfoQty1 = goodsinfoQty1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_qty2
     *
     * @return the value of t_broker_declaration.goodsinfo_qty2
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public BigDecimal getGoodsinfoQty2() {
        return goodsinfoQty2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_qty2
     *
     * @param goodsinfoQty2 the value for t_broker_declaration.goodsinfo_qty2
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoQty2(BigDecimal goodsinfoQty2) {
        this.goodsinfoQty2 = goodsinfoQty2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_destinationcountry
     *
     * @return the value of t_broker_declaration.goodsinfo_destinationcountry
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getGoodsinfoDestinationcountry() {
        return goodsinfoDestinationcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_destinationcountry
     *
     * @param goodsinfoDestinationcountry the value for t_broker_declaration.goodsinfo_destinationcountry
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoDestinationcountry(String goodsinfoDestinationcountry) {
        this.goodsinfoDestinationcountry = goodsinfoDestinationcountry == null ? null : goodsinfoDestinationcountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_origincountry
     *
     * @return the value of t_broker_declaration.goodsinfo_origincountry
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getGoodsinfoOrigincountry() {
        return goodsinfoOrigincountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_origincountry
     *
     * @param goodsinfoOrigincountry the value for t_broker_declaration.goodsinfo_origincountry
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoOrigincountry(String goodsinfoOrigincountry) {
        this.goodsinfoOrigincountry = goodsinfoOrigincountry == null ? null : goodsinfoOrigincountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.goodsinfo_districtcode
     *
     * @return the value of t_broker_declaration.goodsinfo_districtcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getGoodsinfoDistrictcode() {
        return goodsinfoDistrictcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.goodsinfo_districtcode
     *
     * @param goodsinfoDistrictcode the value for t_broker_declaration.goodsinfo_districtcode
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setGoodsinfoDistrictcode(String goodsinfoDistrictcode) {
        this.goodsinfoDistrictcode = goodsinfoDistrictcode == null ? null : goodsinfoDistrictcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.contactperson
     *
     * @return the value of t_broker_declaration.contactperson
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getContactperson() {
        return contactperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.contactperson
     *
     * @param contactperson the value for t_broker_declaration.contactperson
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setContactperson(String contactperson) {
        this.contactperson = contactperson == null ? null : contactperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.contactway
     *
     * @return the value of t_broker_declaration.contactway
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getContactway() {
        return contactway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.contactway
     *
     * @param contactway the value for t_broker_declaration.contactway
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setContactway(String contactway) {
        this.contactway = contactway == null ? null : contactway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.uuid
     *
     * @return the value of t_broker_declaration.uuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.uuid
     *
     * @param uuid the value for t_broker_declaration.uuid
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_broker_declaration.createtime
     *
     * @return the value of t_broker_declaration.createtime
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_broker_declaration.createtime
     *
     * @param createtime the value for t_broker_declaration.createtime
     *
     * @mbggenerated Thu Sep 06 16:31:04 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getCustomsinfoMarkNo() {
        return customsinfoMarkNo;
    }

    public void setCustomsinfoMarkNo(String customsinfoMarkNo) {
        this.customsinfoMarkNo = customsinfoMarkNo;
    }

    private String customsinfoMarkNo;
}