package com.sinochem.crude.trade.shiprefueling.domain.po;

import java.io.Serializable;

import java.util.Date;

public class TDataDict implements Serializable {
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.ID
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.TYPE_code
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.dict_code
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    private String dictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.dict_name
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    private String dictName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.p_dict_code
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    private String pDictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.ALIVE_FLAG
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    private String aliveFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.VERSION
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.LANG_VER
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    private String langVer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.CREATE_DATE
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.UPDATE_DATE
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.CREATE_USER
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.UPDATE_USER
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    private Long updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.ID
     *
     * @return the value of t_data_dict.ID
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.ID
     *
     * @param id the value for t_data_dict.ID
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.TYPE_code
     *
     * @return the value of t_data_dict.TYPE_code
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.TYPE_code
     *
     * @param typeCode the value for t_data_dict.TYPE_code
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.dict_code
     *
     * @return the value of t_data_dict.dict_code
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.dict_code
     *
     * @param dictCode the value for t_data_dict.dict_code
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.dict_name
     *
     * @return the value of t_data_dict.dict_name
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.dict_name
     *
     * @param dictName the value for t_data_dict.dict_name
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.p_dict_code
     *
     * @return the value of t_data_dict.p_dict_code
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public String getpDictCode() {
        return pDictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.p_dict_code
     *
     * @param pDictCode the value for t_data_dict.p_dict_code
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public void setpDictCode(String pDictCode) {
        this.pDictCode = pDictCode == null ? null : pDictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.ALIVE_FLAG
     *
     * @return the value of t_data_dict.ALIVE_FLAG
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public String getAliveFlag() {
        return aliveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.ALIVE_FLAG
     *
     * @param aliveFlag the value for t_data_dict.ALIVE_FLAG
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public void setAliveFlag(String aliveFlag) {
        this.aliveFlag = aliveFlag == null ? null : aliveFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.VERSION
     *
     * @return the value of t_data_dict.VERSION
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.VERSION
     *
     * @param version the value for t_data_dict.VERSION
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.LANG_VER
     *
     * @return the value of t_data_dict.LANG_VER
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public String getLangVer() {
        return langVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.LANG_VER
     *
     * @param langVer the value for t_data_dict.LANG_VER
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public void setLangVer(String langVer) {
        this.langVer = langVer == null ? null : langVer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.CREATE_DATE
     *
     * @return the value of t_data_dict.CREATE_DATE
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.CREATE_DATE
     *
     * @param createDate the value for t_data_dict.CREATE_DATE
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.UPDATE_DATE
     *
     * @return the value of t_data_dict.UPDATE_DATE
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.UPDATE_DATE
     *
     * @param updateDate the value for t_data_dict.UPDATE_DATE
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.CREATE_USER
     *
     * @return the value of t_data_dict.CREATE_USER
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.CREATE_USER
     *
     * @param createUser the value for t_data_dict.CREATE_USER
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.UPDATE_USER
     *
     * @return the value of t_data_dict.UPDATE_USER
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.UPDATE_USER
     *
     * @param updateUser the value for t_data_dict.UPDATE_USER
     *
     * @mbggenerated Mon Jul 23 16:18:25 CST 2018
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }
}